### ISSUE TITLE
[Bug] Problem in getBestiarySpellLevel

### ISSUE THREAD

**Issue by xdy** [WBHarry/pf2e-bestiary-tracking#149]
Got this last night when playing during a fight with the pcs, a haunt and some geists. Not sure what creature caused the problem as I just quickly patched the code.
```
2BestiaryTracking.js:356 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'spells')
[Detected 1 package: pf2e-bestiary-tracking(1.1.25)]
    at getBestiarySpellLevel (BestiaryTracking.js:356:31)
    at updateBestiaryData (BestiaryTracking.js:18358:13)
```
The patch I did was to change line 356 to this, but it's possibly spells should be checked earlier.
```
if (spells.levels && spells.levels[maxLevel].spells[id]) return maxLevel;
```
and change 360 to this
```
if (spells.levels[level]?.spells[id]) {
```

**Comment by WBHarry** [comment]
Heya. You don't happen to know the specific haunt/geists involved?
The fixes you made would stop the errors, but it wouldn't make the functionality in that section of the code actually do what it's supposed to (automatically reveal the spells being cast in the Bestiary).

It seems whichever creatures were present didn't get their spells added to the Bestiary properly 🤔

**Comment by xdy** [comment]
Thought I had replied, but, apparently not. It was from Curtain Call book 1, chapter 2, room C2 the Workshop, 4 Geist (from Book of the Dead) and one Mocking Puppets (from Curtain Call). Neither of them have spells, so I don't know how they even got to that part of the code.

**Comment by xdy** [comment]
The same thing happened again during another couple of fights in Curtain Call (Ockomlire and Risen Graverobbers) so it might be that actors in that are bad (or were, they might have been updated since I imported book 1).

**Comment by WBHarry** [comment]
That, or I have something to fix 😁 
It's not really a main intended way for the Bestiary to be used, but since you can add Player Characters into the Bestiary, it shouldn't throw such an error.

If you could export the player characters and toss them my way I could debug the issue.
![image](https://github.com/user-attachments/assets/b4db6970-d471-4641-9a09-3aab77ca0f17)

**Comment by xdy** [comment]
[party.zip](https://github.com/user-attachments/files/17951772/party.zip)

**Comment by WBHarry** [comment]
I finally got around to adding a fix for this in v 1.1.29 🤖 👍
